[supabase]
url = "https://hmrftqougofiigklkave.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmZ0cW91Z29maWlna2xrYXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjM3NDAsImV4cCI6MjA2MDI5OTc0MH0.BH4p0snIv2byyR_875F8pfcDM0RiuwrlRfV-jQt1APs"
